// JSRS All Rights Reserved

#pragma once

#include  "NativeGameplayTags.h"

namespace MStudyGameplayTags
{
	// UI Widget Stack
	MENUSTUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_Modal);
	MENUSTUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_GameMenu);
	MENUSTUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_GameHud);
	MENUSTUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_Frontend);

	// UI Widgets
	MENUSTUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_PressAnyKeyScreen);
	MENUSTUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_MainMenu);
	MENUSTUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_ConfirmScreen);
}